#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Re-render the Aranya brochure pages into web-optimised WebP assets.

Every 1920x1387 PNG in public/assets/ is a render of exactly one page of
`Aranya _E_Brochure 2.pdf` (pages are 1296x936 pt, ratio 1.385). Those PNGs are
low-resolution and enormous (71 MB total). This script re-renders each page
straight from the PDF at high DPI and writes a responsive set of WebP files,
plus a manifest the app uses for srcSet and intrinsic width/height.

Usage:  python scripts/extract-brochure-assets.py
Needs:  PyMuPDF (fitz) + Pillow
"""

import io
import os
import sys

try:
    import fitz  # PyMuPDF
except ImportError:
    sys.exit('PyMuPDF is required:  pip install PyMuPDF')
from PIL import Image

PDF = 'Aranya _E_Brochure 2.pdf'
OUT = 'public/assets/opt'
MANIFEST = 'src/data/imageManifest.ts'

# Responsive widths per asset kind.
#   spread — both brochure pages are shown, so the text half must stay legible
#   photo  — full-bleed photograph, displayed in a card or full-bleed band
#   plan   — blueprint, needs detail because FloorPlans zooms up to 2.25x
WIDTHS = {
    'spread': [900, 1600, 2800],
    'photo':  [640, 1280, 2000],
    'plan':   [800, 1600, 2600],
}

# asset basename -> (1-based PDF page, kind). Verified by matching every
# 1920x1387 PNG against a render of each page; all 29 matched a distinct page.
PAGES = {
    'lifestyle-living':             (3,  'photo'),
    'lifestyle-sundeck':            (4,  'photo'),
    'lifestyle-park-greens':        (5,  'spread'),
    'hero-elevation':               (6,  'spread'),
    'location-map-infra':           (7,  'spread'),
    'connectivity-conveniences':    (8,  'spread'),
    'residences-interior':          (9,  'photo'),
    'grand-lobby':                  (10, 'photo'),
    'amenities-overview':           (11, 'spread'),
    'amenity-pickleball':           (12, 'photo'),
    'amenity-senior-citizens':      (13, 'photo'),
    'amenity-kids-play':            (14, 'photo'),
    'amenity-fitness-center':       (15, 'photo'),
    'amenity-rooftop-yoga':         (16, 'photo'),
    'amenity-games-room':           (17, 'photo'),
    'amenity-banquet-gazebo':       (18, 'photo'),
    'project-specifications':       (19, 'spread'),
    'master-layout-plan':           (20, 'plan'),
    'plan-clubhouse-ground':        (21, 'plan'),
    'plan-tower-a-ground-terrace':  (22, 'plan'),
    'plan-tower-a-2nd-3rd':         (23, 'plan'),
    'plan-tower-a-typical':         (24, 'plan'),
    'plan-tower-a-upper':           (25, 'plan'),
    'plan-tower-b-ground-terrace':  (26, 'plan'),
    'plan-tower-b-typical':         (27, 'plan'),
    'plan-tower-b-upper':           (28, 'plan'),
    'developer-profile':            (29, 'spread'),
    'consultant-partners':          (30, 'spread'),
}

QUALITY = 82


def render(page, width):
    """Render a PDF page to a PIL image of the given pixel width."""
    zoom = width / page.rect.width
    pm = page.get_pixmap(matrix=fitz.Matrix(zoom, zoom), alpha=False)
    return Image.frombytes('RGB', (pm.width, pm.height), pm.samples)


def main():
    if not os.path.exists(PDF):
        sys.exit('Cannot find %s — run from the project root.' % PDF)

    os.makedirs(OUT, exist_ok=True)
    doc = fitz.open(PDF)
    entries = []
    total = 0

    for name, (pno, kind) in sorted(PAGES.items(), key=lambda kv: kv[1][0]):
        page = doc[pno - 1]
        widths = WIDTHS[kind]
        srcset = []
        biggest = None

        for w in widths:
            im = render(page, w)
            path = '%s/%s-%d.webp' % (OUT, name, w)
            im.save(path, 'WEBP', quality=QUALITY, method=6)
            total += os.path.getsize(path)
            srcset.append('/assets/opt/%s-%d.webp %dw' % (name, w, w))
            biggest = (w, im.height)

        entries.append((
            '/assets/opt/%s-%d.webp' % (name, widths[-1]),
            ', '.join(srcset),
            biggest[0], biggest[1], kind,
        ))
        print('  %-30s p%-3d %-6s %s' % (name, pno, kind,
              ' '.join(str(w) for w in widths)))

    with io.open(MANIFEST, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write('// AUTO-GENERATED by scripts/extract-brochure-assets.py — do not edit.\n')
        fh.write('// Re-run the script after changing the brochure or the width presets.\n\n')
        fh.write('export interface ManifestEntry {\n')
        fh.write('  srcSet: string;\n  width: number;\n  height: number;\n')
        fh.write("  kind: 'spread' | 'photo' | 'plan';\n}\n\n")
        fh.write('export const imageManifest: Record<string, ManifestEntry> = {\n')
        for src, srcset, w, h, kind in entries:
            fh.write("  '%s': {\n" % src)
            fh.write("    srcSet: '%s',\n" % srcset)
            fh.write('    width: %d,\n    height: %d,\n' % (w, h))
            fh.write("    kind: '%s',\n  },\n" % kind)
        fh.write('};\n')

    print('\n  %d assets, %d files, %.1f MB total' %
          (len(entries), len(entries) * 3, total / 1048576.0))
    print('  manifest -> %s' % MANIFEST)


if __name__ == '__main__':
    main()
