// AUTO-GENERATED by scripts/extract-brochure-assets.py — do not edit.
// Re-run the script after changing the brochure or the width presets.

export interface ManifestEntry {
  srcSet: string;
  width: number;
  height: number;
  kind: 'spread' | 'photo' | 'plan';
}

export const imageManifest: Record<string, ManifestEntry> = {
  '/assets/opt/lifestyle-living-2000.webp': {
    srcSet: '/assets/opt/lifestyle-living-640.webp 640w, /assets/opt/lifestyle-living-1280.webp 1280w, /assets/opt/lifestyle-living-2000.webp 2000w',
    width: 2000,
    height: 1445,
    kind: 'photo',
  },
  '/assets/opt/lifestyle-sundeck-2000.webp': {
    srcSet: '/assets/opt/lifestyle-sundeck-640.webp 640w, /assets/opt/lifestyle-sundeck-1280.webp 1280w, /assets/opt/lifestyle-sundeck-2000.webp 2000w',
    width: 2000,
    height: 1445,
    kind: 'photo',
  },
  '/assets/opt/lifestyle-park-greens-2800.webp': {
    srcSet: '/assets/opt/lifestyle-park-greens-900.webp 900w, /assets/opt/lifestyle-park-greens-1600.webp 1600w, /assets/opt/lifestyle-park-greens-2800.webp 2800w',
    width: 2800,
    height: 2023,
    kind: 'spread',
  },
  '/assets/opt/hero-elevation-2800.webp': {
    srcSet: '/assets/opt/hero-elevation-900.webp 900w, /assets/opt/hero-elevation-1600.webp 1600w, /assets/opt/hero-elevation-2800.webp 2800w',
    width: 2800,
    height: 2023,
    kind: 'spread',
  },
  '/assets/opt/location-map-infra-2800.webp': {
    srcSet: '/assets/opt/location-map-infra-900.webp 900w, /assets/opt/location-map-infra-1600.webp 1600w, /assets/opt/location-map-infra-2800.webp 2800w',
    width: 2800,
    height: 2023,
    kind: 'spread',
  },
  '/assets/opt/connectivity-conveniences-2800.webp': {
    srcSet: '/assets/opt/connectivity-conveniences-900.webp 900w, /assets/opt/connectivity-conveniences-1600.webp 1600w, /assets/opt/connectivity-conveniences-2800.webp 2800w',
    width: 2800,
    height: 2023,
    kind: 'spread',
  },
  '/assets/opt/residences-interior-2000.webp': {
    srcSet: '/assets/opt/residences-interior-640.webp 640w, /assets/opt/residences-interior-1280.webp 1280w, /assets/opt/residences-interior-2000.webp 2000w',
    width: 2000,
    height: 1445,
    kind: 'photo',
  },
  '/assets/opt/grand-lobby-2000.webp': {
    srcSet: '/assets/opt/grand-lobby-640.webp 640w, /assets/opt/grand-lobby-1280.webp 1280w, /assets/opt/grand-lobby-2000.webp 2000w',
    width: 2000,
    height: 1445,
    kind: 'photo',
  },
  '/assets/opt/amenities-overview-2800.webp': {
    srcSet: '/assets/opt/amenities-overview-900.webp 900w, /assets/opt/amenities-overview-1600.webp 1600w, /assets/opt/amenities-overview-2800.webp 2800w',
    width: 2800,
    height: 2023,
    kind: 'spread',
  },
  '/assets/opt/amenity-pickleball-2000.webp': {
    srcSet: '/assets/opt/amenity-pickleball-640.webp 640w, /assets/opt/amenity-pickleball-1280.webp 1280w, /assets/opt/amenity-pickleball-2000.webp 2000w',
    width: 2000,
    height: 1445,
    kind: 'photo',
  },
  '/assets/opt/amenity-senior-citizens-2000.webp': {
    srcSet: '/assets/opt/amenity-senior-citizens-640.webp 640w, /assets/opt/amenity-senior-citizens-1280.webp 1280w, /assets/opt/amenity-senior-citizens-2000.webp 2000w',
    width: 2000,
    height: 1445,
    kind: 'photo',
  },
  '/assets/opt/amenity-kids-play-2000.webp': {
    srcSet: '/assets/opt/amenity-kids-play-640.webp 640w, /assets/opt/amenity-kids-play-1280.webp 1280w, /assets/opt/amenity-kids-play-2000.webp 2000w',
    width: 2000,
    height: 1445,
    kind: 'photo',
  },
  '/assets/opt/amenity-fitness-center-2000.webp': {
    srcSet: '/assets/opt/amenity-fitness-center-640.webp 640w, /assets/opt/amenity-fitness-center-1280.webp 1280w, /assets/opt/amenity-fitness-center-2000.webp 2000w',
    width: 2000,
    height: 1445,
    kind: 'photo',
  },
  '/assets/opt/amenity-rooftop-yoga-2000.webp': {
    srcSet: '/assets/opt/amenity-rooftop-yoga-640.webp 640w, /assets/opt/amenity-rooftop-yoga-1280.webp 1280w, /assets/opt/amenity-rooftop-yoga-2000.webp 2000w',
    width: 2000,
    height: 1445,
    kind: 'photo',
  },
  '/assets/opt/amenity-games-room-2000.webp': {
    srcSet: '/assets/opt/amenity-games-room-640.webp 640w, /assets/opt/amenity-games-room-1280.webp 1280w, /assets/opt/amenity-games-room-2000.webp 2000w',
    width: 2000,
    height: 1445,
    kind: 'photo',
  },
  '/assets/opt/amenity-banquet-gazebo-2000.webp': {
    srcSet: '/assets/opt/amenity-banquet-gazebo-640.webp 640w, /assets/opt/amenity-banquet-gazebo-1280.webp 1280w, /assets/opt/amenity-banquet-gazebo-2000.webp 2000w',
    width: 2000,
    height: 1445,
    kind: 'photo',
  },
  '/assets/opt/project-specifications-2800.webp': {
    srcSet: '/assets/opt/project-specifications-900.webp 900w, /assets/opt/project-specifications-1600.webp 1600w, /assets/opt/project-specifications-2800.webp 2800w',
    width: 2800,
    height: 2023,
    kind: 'spread',
  },
  '/assets/opt/master-layout-plan-2600.webp': {
    srcSet: '/assets/opt/master-layout-plan-800.webp 800w, /assets/opt/master-layout-plan-1600.webp 1600w, /assets/opt/master-layout-plan-2600.webp 2600w',
    width: 2600,
    height: 1878,
    kind: 'plan',
  },
  '/assets/opt/plan-clubhouse-ground-2600.webp': {
    srcSet: '/assets/opt/plan-clubhouse-ground-800.webp 800w, /assets/opt/plan-clubhouse-ground-1600.webp 1600w, /assets/opt/plan-clubhouse-ground-2600.webp 2600w',
    width: 2600,
    height: 1878,
    kind: 'plan',
  },
  '/assets/opt/plan-tower-a-ground-terrace-2600.webp': {
    srcSet: '/assets/opt/plan-tower-a-ground-terrace-800.webp 800w, /assets/opt/plan-tower-a-ground-terrace-1600.webp 1600w, /assets/opt/plan-tower-a-ground-terrace-2600.webp 2600w',
    width: 2600,
    height: 1878,
    kind: 'plan',
  },
  '/assets/opt/plan-tower-a-2nd-3rd-2600.webp': {
    srcSet: '/assets/opt/plan-tower-a-2nd-3rd-800.webp 800w, /assets/opt/plan-tower-a-2nd-3rd-1600.webp 1600w, /assets/opt/plan-tower-a-2nd-3rd-2600.webp 2600w',
    width: 2600,
    height: 1878,
    kind: 'plan',
  },
  '/assets/opt/plan-tower-a-typical-2600.webp': {
    srcSet: '/assets/opt/plan-tower-a-typical-800.webp 800w, /assets/opt/plan-tower-a-typical-1600.webp 1600w, /assets/opt/plan-tower-a-typical-2600.webp 2600w',
    width: 2600,
    height: 1878,
    kind: 'plan',
  },
  '/assets/opt/plan-tower-a-upper-2600.webp': {
    srcSet: '/assets/opt/plan-tower-a-upper-800.webp 800w, /assets/opt/plan-tower-a-upper-1600.webp 1600w, /assets/opt/plan-tower-a-upper-2600.webp 2600w',
    width: 2600,
    height: 1878,
    kind: 'plan',
  },
  '/assets/opt/plan-tower-b-ground-terrace-2600.webp': {
    srcSet: '/assets/opt/plan-tower-b-ground-terrace-800.webp 800w, /assets/opt/plan-tower-b-ground-terrace-1600.webp 1600w, /assets/opt/plan-tower-b-ground-terrace-2600.webp 2600w',
    width: 2600,
    height: 1878,
    kind: 'plan',
  },
  '/assets/opt/plan-tower-b-typical-2600.webp': {
    srcSet: '/assets/opt/plan-tower-b-typical-800.webp 800w, /assets/opt/plan-tower-b-typical-1600.webp 1600w, /assets/opt/plan-tower-b-typical-2600.webp 2600w',
    width: 2600,
    height: 1878,
    kind: 'plan',
  },
  '/assets/opt/plan-tower-b-upper-2600.webp': {
    srcSet: '/assets/opt/plan-tower-b-upper-800.webp 800w, /assets/opt/plan-tower-b-upper-1600.webp 1600w, /assets/opt/plan-tower-b-upper-2600.webp 2600w',
    width: 2600,
    height: 1878,
    kind: 'plan',
  },
  '/assets/opt/developer-profile-2800.webp': {
    srcSet: '/assets/opt/developer-profile-900.webp 900w, /assets/opt/developer-profile-1600.webp 1600w, /assets/opt/developer-profile-2800.webp 2800w',
    width: 2800,
    height: 2023,
    kind: 'spread',
  },
  '/assets/opt/consultant-partners-2800.webp': {
    srcSet: '/assets/opt/consultant-partners-900.webp 900w, /assets/opt/consultant-partners-1600.webp 1600w, /assets/opt/consultant-partners-2800.webp 2800w',
    width: 2800,
    height: 2023,
    kind: 'spread',
  },
};
